#!/usr/bin/env zsh
autoload -Uz compinit
# autoload -Uz bashcompinit
compinit -C
# bashcompinit -C
source ~/dotfiles/zsh/zsh-autosuggestions.zsh
source ~/dotfiles/zsh/git.zsh
source ~/dotfiles/zsh/completion.zsh
source ~/dotfiles/zsh/starship.zsh
source ~/dotfiles/zsh/zoxide.zsh
source ~/dotfiles/zsh/key-bindings.zsh
if [ ! -e ~/dotfiles/zsh/fzf.zsh ]; then
	fzf --zsh > ~/dotfiles/zsh/fzf.zsh
	zcompile ~/dotfiles/zsh/fzf.zsh
fi
source ~/dotfiles/zsh/fzf.zsh
if [ ! -e ~/dotfiles/zsh/direnv.zsh ]; then
	direnv hook zsh > ~/dotfiles/zsh/direnv.zsh
	zcompile ~/dotfiles/zsh/direnv.zsh
fi
source ~/dotfiles/zsh/direnv.zsh
source ~/dotfiles/zsh/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

function precmd() {
  print -P "\e]7;file://${HOSTNAME}${PWD}\a"
}

export EDITOR="hx"
export VISUAL="hx"

alias cd="z"
alias lg="lazygit"

function r() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		z -- "$cwd"
	fi
	rm -f -- "$tmp"
}

function dl() {
	it=$(ls -t ~/Downloads | head -n1)
	echo "$it"
	mv ~/Downloads/"$it" .
}

if [ $(hostname) = "estella" ]; then
	pkgs_path=server
else
	pkgs_path=graphical
fi
function pkg() {
	hx ~/dotfiles/nix-config/sys/$pkgs_path.nix:$(grep --line-number "with pkgs" ~/dotfiles/nix-config/sys/$pkgs_path.nix | head -n1 | cut -d: -f1) ~/dotfiles/nix-config/sys/common.nix:$(grep --line-number "with pkgs" ~/dotfiles/nix-config/sys/common.nix | head -n1 | cut -d: -f1) ~/dotfiles/nix-config/flake.nix ~/dotfiles/nix-config/sys/$(hostname).nix 
	env -C ~/dotfiles just nix
}

function take() {
	mkdir "$1" && cd "$1"
}

alias zshrc="hx ~/.zshrc; source ~/.zshrc"
